In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /opt/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [3]:
cpp_39_data  = pd.read_excel("./datasets/CPP_long_6-21-21.xlsx")

In [4]:
cpp_39_data.head()

,scrapedate,lastupdated,stateagency,facility,fac_inc_positive,fac_inc_activeasymptomatic,sum_inc_tested,fac_inc_activesymptomatic,sum_inc_hospitalized,sum_inc_recovered,...,bjs_fac_security,bjs_fac_leave,bjs_fac_operator,bjs_fac_malepop,bjs_fac_femalepop,bjs_fac_linked,bjs_fac_linktxt,bjs_fac_changeuse,bjs_fac_changeclose,oldnew
0,2020-05-22,NR,CT,Bridgeport CC,66.0,NR,NR,NR,NR,NR,...,Maximum/close/high,None,State authority,865.0,NR,No,NR,No,No,old
1,2020-05-22,NaN,CT,Brooklyn CI,19.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,old
2,2020-05-22,NaN,CT,Carl Robinson CI,75.0,NaN,NaN,NaN,NaN,NaN,...,Medium,None,State authority,1459.0,NaN,No,NaN,No,No,old
3,2020-05-22,NaN,CT,Cheshire CI,18.0,NaN,NaN,NaN,NaN,NaN,...,Maximum/close/high,None,State authority,1471.0,NaN,No,NaN,No,No,old
4,2020-05-22,NaN,CT,Corrigan-Radgowski,110.0,NaN,NaN,NaN,NaN,NaN,...,Maximum/close/high,None,State authority,1556.0,NaN,No,NaN,No,No,old

In [5]:
cpp_39_data.shape

(5849, 48)

In [6]:
facility = pd.read_csv("./datasets/facilities.csv")

In [7]:
facility.head()

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
0,F3EFE858,Alex City Work Release prison,Low-security work release,Alex City,Coosa,1037,Alabama,-86.009015,32.904507,188.0,NaN,77,0,17,0.0,NaN
1,5B910220,Alabama Therapeutic Education Facility prison,State rehabilitation center,Columbiana,Shelby,1117,Alabama,-86.624067,33.180755,272.0,NaN,11,1,2,0.0,NaN
2,02FB1675,Bibb Correctional Facility,State prison,Brent,Bibb,1007,Alabama,-87.162781,32.920754,1725.0,1825.0,164,3,61,0.0,NaN
3,6378F6C4,Birmingham Women's Community Based Facility an...,State prison,Birmingham,Jefferson,1073,Alabama,-86.808344,33.531101,192.0,NaN,17,0,28,0.0,NaN
4,EAABF900,Bullock Correctional Facility,State prison,Bessemer,Bullock,1011,Alabama,-85.673927,32.147144,1477.0,1577.0,162,5,80,1.0,NaN

In [8]:
facility.shape

(2639, 16)

In [9]:
facility.isna().sum()

nyt_id                           0
facility_name                    0
facility_type                    0
facility_city                   10
facility_county                  0
facility_county_fips             0
facility_state                   1
facility_lng                     0
facility_lat                     0
latest_inmate_population      1046
max_inmate_population_2020    1801
total_inmate_cases               0
total_inmate_deaths              0
total_officer_cases              0
total_officer_deaths             1
note                          2599
dtype: int64

In [10]:
faci = facility.loc[:, ["facility_state", "facility_county","facility_type", "total_inmate_cases", "total_inmate_deaths"]]

In [11]:
faci.head()

,facility_state,facility_county,facility_type,total_inmate_cases,total_inmate_deaths
0,Alabama,Coosa,Low-security work release,77,0
1,Alabama,Shelby,State rehabilitation center,11,1
2,Alabama,Bibb,State prison,164,3
3,Alabama,Jefferson,State prison,17,0
4,Alabama,Bullock,State prison,162,5

In [12]:
facility["facility_type"].value_counts()

State prison                   1071
Jail                            833
State juvenile detention        173
Detention center                163
Federal halfway house           140
Federal prison                  111
State work camp                  39
State facility                   33
State rehabilitation center      25
State halfway house              22
Low-security work release        19
Juvenile detention at jail        8
Reservation jail                  1
U.S. Marshalls                    1
Name: facility_type, dtype: int64

In [13]:
bod_dt = pd.read_csv("./datasets/BOP Texas.csv")

In [14]:
bod_dt.head()

,scrapedate,lastupdated,stateagency,facility,fac_city,fac_state,facilitytype,fac_inc_positive,fac_inc_active,fac_inc_recovered,...,bjs_fac_operator,bjs_fac_malepop,bjs_fac_femalepop,bjs_fac_linked,bjs_fac_linkTexast,bjs_fac_changeuse,bjs_fac_changeclose,bjs_fac_notes,bjs_fac_notes2,oldnew
0,03/18/2020,NR,BOP,ACS Corrections (RRC),Del Valle,Texas,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,old
1,03/18/2020,NaN,BOP,Bastrop FCI,Bastrop,Texas,NaN,NaN,NaN,NaN,...,Federal Bureau of Prisons,1215,NaN,Yes,Bastrop-Camp,No,No,NaN,NaN,old
2,03/18/2020,NaN,BOP,Beaumont Low FCI,Beaumont,Texas,NaN,NaN,NaN,NaN,...,Federal Bureau of Prisons,2000,NaN,No,NaN,No,No,Complex = Beaumont FCC,NaN,old
3,03/18/2020,NaN,BOP,Beaumont Medium FCI,Beaumont,Texas,NaN,NaN,NaN,NaN,...,Federal Bureau of Prisons,1560,NaN,No,NaN,No,No,Complex = Beaumont FCC,NaN,old
4,03/18/2020,NaN,BOP,Beaumont USP,Beaumont,Texas,NaN,NaN,NaN,NaN,...,Federal Bureau of Prisons,1479,NaN,Yes,Beaumont USP-Camp,No,No,Complex = Beaumont FCC,NaN,old

In [15]:
bod_dt.shape

(16149, 59)

In [16]:
bod_dt.tail()

,scrapedate,lastupdated,stateagency,facility,fac_city,fac_state,facilitytype,fac_inc_positive,fac_inc_active,fac_inc_recovered,...,bjs_fac_operator,bjs_fac_malepop,bjs_fac_femalepop,bjs_fac_linked,bjs_fac_linkTexast,bjs_fac_changeuse,bjs_fac_changeclose,bjs_fac_notes,bjs_fac_notes2,oldnew
16144,06/21/2021,6/17/2021,BOP,"Volunteers of America Texas, Inc. (RRC)",hutchins,Texas,Public,9,0,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16145,06/21/2021,6/17/2021,BOP,Big Spring (Flightline) CI,big spring,Texas,Private,33,0,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16146,06/21/2021,6/17/2021,BOP,Big Spring CI,big spring,Texas,Private,531,0,531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16147,06/21/2021,6/17/2021,BOP,Giles W. Dalby CI,post,Texas,Private,97,0,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16148,06/21/2021,6/17/2021,BOP,Reeves III CI,pecos,Texas,Private,32,0,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
bod_dt.columns

Index(['scrapedate', 'lastupdated', 'stateagency', 'facility', 'fac_city',
       'fac_state', 'facilitytype', 'fac_inc_positive', 'fac_inc_active',
       'fac_inc_recovered', 'fac_inc_deaths', 'fac_staff_positive',
       'fac_staff_active', 'fac_staff_recovered', 'fac_staff_deaths',
       'fac_inc_tested', 'fac_inc_pending', 'fac_inc_positivetests',
       'fac_staff_vaccinated', 'fac_inc_vaccinated', 'sum_inc_population',
       'sum_inc_population_bopmanaged', 'sum_inc_population_community',
       'sum_staff_population', 'facility_bjs', 'fac_address', 'fac_zip',
       'fac_facilitytype', 'sum_inc_pop', 'sum_inc_positive', 'sum_inc_deaths',
       'sum_inc_tested', 'sum_inc_pop_bopmanaged', 'sum_inc_pop_community',
       'sum_staff_deaths', 'sum_staff_positive', 'sum_staff_pop', 'match',
       'bjs_fac_state', 'bjs_fac_id', 'bjs_fac_id2', 'bjs_fac_name',
       'bjs_fac_address1', 'bjs_fac_city', 'bjs_fac_stateab', 'bjs_fac_zip1',
       'bjs_fac_gender', 'bjs_fac_security', 'bjs_fac_leave',
       'bjs_fac_operator', 'bjs_fac_malepop', 'bjs_fac_femalepop',
       'bjs_fac_linked', 'bjs_fac_linkTexast', 'bjs_fac_changeuse',
       'bjs_fac_changeclose', 'bjs_fac_notes', 'bjs_fac_notes2', 'oldnew'],
      dtype='object')

In [18]:
drop_features = ["scrapedate", "lastupdated", "stateagency", "fac_state","bjs_fac_changeuse",
                "bjs_fac_operator", "bjs_fac_linked", "bjs_fac_linkTexast",
                "fac_staff_positive", "fac_staff_active", "fac_staff_recovered",
                "fac_staff_deaths", "fac_staff_vaccinated", "sum_staff_population",
                "bjs_fac_id", "fac_address", "fac_zip", "bjs_fac_security",'bjs_fac_state', 'bjs_fac_id', 'bjs_fac_id2', 'bjs_fac_name',
       'bjs_fac_address1', 'bjs_fac_city', 'bjs_fac_stateab', 'bjs_fac_zip1', 'bjs_fac_security', 'bjs_fac_leave',
       'bjs_fac_operator',
       'bjs_fac_linked', 'bjs_fac_linkTexast', 'bjs_fac_changeuse',
       'bjs_fac_changeclose', 'bjs_fac_notes', 'bjs_fac_notes2' ]

In [19]:
bod_dt = bod_dt.drop(columns = drop_features, axis = 1)

In [20]:
bod_dt.head()

,facility,fac_city,facilitytype,fac_inc_positive,fac_inc_active,fac_inc_recovered,fac_inc_deaths,fac_inc_tested,fac_inc_pending,fac_inc_positivetests,...,sum_inc_pop_bopmanaged,sum_inc_pop_community,sum_staff_deaths,sum_staff_positive,sum_staff_pop,match,bjs_fac_gender,bjs_fac_malepop,bjs_fac_femalepop,oldnew
0,ACS Corrections (RRC),Del Valle,NR,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,0.0,0.0,NR,not in BJS,NR,NR,NR,old
1,Bastrop FCI,Bastrop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,in BJS (matched),Males only,1215,NaN,old
2,Beaumont Low FCI,Beaumont,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,in BJS (matched),Males only,2000,NaN,old
3,Beaumont Medium FCI,Beaumont,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,in BJS (matched),Males only,1560,NaN,old
4,Beaumont USP,Beaumont,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,in BJS (matched),Males only,1479,NaN,old

In [21]:
bod_dt.shape

(16149, 30)

In [22]:
bod_dt.isna().sum()

facility                             0
fac_city                          4927
facilitytype                     13163
fac_inc_positive                  6197
fac_inc_active                    6616
fac_inc_recovered                 6756
fac_inc_deaths                    6616
fac_inc_tested                    9877
fac_inc_pending                   9877
fac_inc_positivetests            11849
fac_inc_vaccinated               15984
sum_inc_population               16148
sum_inc_population_bopmanaged    16148
sum_inc_population_community     16148
facility_bjs                     11211
fac_facilitytype                 16148
sum_inc_pop                      13347
sum_inc_positive                     0
sum_inc_deaths                    2985
sum_inc_tested                    5133
sum_inc_pop_bopmanaged           13347
sum_inc_pop_community            13439
sum_staff_deaths                  2985
sum_staff_positive                2985
sum_staff_pop                    13163
match                             2985
bjs_fac_gender                   11211
bjs_fac_malepop                  12237
bjs_fac_femalepop                15122
oldnew                            2985
dtype: int64

In [23]:
bod_dt.dropna(thresh = 9, inplace = True)

In [24]:
bod_dt["bjs_fac_gender"].value_counts()

Males only      3911
Females only    1026
NR                 1
Name: bjs_fac_gender, dtype: int64

In [25]:
bod_dt.shape

(11996, 30)

In [26]:
bod_dt["bjs_fac_gender"].isna().sum()

7058

In [27]:
data = pd.read_csv("./datasets/systems.csv.txt")

In [28]:
data.head()

,system,inmate_tests,total_inmate_cases,total_inmate_deaths,latest_inmate_population,max_inmate_population_2020,total_officer_cases,total_officer_deaths
0,Alabama,15505.0,1601,64,19144.0,21900.0,1019.0,3.0
1,Alaska,27756.0,2428,5,5011.0,5143.0,85.0,0.0
2,Arizona,43652.0,12229,44,38248.0,41674.0,2739.0,0.0
3,Arkansas,0.0,11378,52,14729.0,15886.0,424.0,5.0
4,California,121207.0,49511,217,110471.0,117767.0,16090.0,26.0

In [29]:
data.columns

Index(['system', 'inmate_tests', 'total_inmate_cases', 'total_inmate_deaths',
       'latest_inmate_population', 'max_inmate_population_2020',
       'total_officer_cases', 'total_officer_deaths'],
      dtype='object')

In [30]:
data.groupby("system").describe()

                      inmate_tests                                    \
                             count      mean std       min       25%
system
Alabama                        1.0   15505.0 NaN   15505.0   15505.0
Alaska                         1.0   27756.0 NaN   27756.0   27756.0
Arizona                        1.0   43652.0 NaN   43652.0   43652.0
Arkansas                       1.0       0.0 NaN       0.0       0.0
California                     1.0  121207.0 NaN  121207.0  121207.0
Colorado                       1.0  193165.0 NaN  193165.0  193165.0
Connecticut                    1.0   73559.0 NaN   73559.0   73559.0
County jails                   1.0  460887.0 NaN  460887.0  460887.0
Delaware                       1.0   12665.0 NaN   12665.0   12665.0
Federal Prisons                1.0  119449.0 NaN  119449.0  119449.0
Florida                        1.0   87677.0 NaN   87677.0   87677.0
Georgia                        1.0   11947.0 NaN   11947.0   11947.0
Hawaii                         1.0    7791.0 NaN    7791.0    7791.0
ICE detention centers          1.0  101214.0 NaN  101214.0  101214.0
Idaho                          1.0   29168.0 NaN   29168.0   29168.0
Illinois                       1.0  477218.0 NaN  477218.0  477218.0
Indiana                        1.0   20228.0 NaN   20228.0   20228.0
Iowa                           1.0   44262.0 NaN   44262.0   44262.0
Kansas                         1.0   43391.0 NaN   43391.0   43391.0
Kentucky                       1.0   26433.0 NaN   26433.0   26433.0
Louisiana                      1.0   14745.0 NaN   14745.0   14745.0
Maine                          1.0    8246.0 NaN    8246.0    8246.0
Maryland                       1.0   65158.0 NaN   65158.0   65158.0
Massachusetts                  1.0   29016.0 NaN   29016.0   29016.0
Michigan                       1.0  673822.0 NaN  673822.0  673822.0
Minnesota                      1.0  105390.0 NaN  105390.0  105390.0
Mississippi                    1.0    3433.0 NaN    3433.0    3433.0
Missouri                       1.0   92520.0 NaN   92520.0   92520.0
Montana                        1.0       0.0 NaN       0.0       0.0
Nebraska                       1.0    6776.0 NaN    6776.0    6776.0
Nevada                         1.0   12368.0 NaN   12368.0   12368.0
New Hampshire                  1.0    1583.0 NaN    1583.0    1583.0
New Jersey                     1.0  251841.0 NaN  251841.0  251841.0
New Mexico                     1.0   44368.0 NaN   44368.0   44368.0
New York                       1.0   73607.0 NaN   73607.0   73607.0
North Carolina                 1.0  124617.0 NaN  124617.0  124617.0
North Dakota                   1.0   32531.0 NaN   32531.0   32531.0
Ohio                           1.0   56275.0 NaN   56275.0   56275.0
Oklahoma                       1.0   30802.0 NaN   30802.0   30802.0
Oregon                         1.0   24852.0 NaN   24852.0   24852.0
Pennsylvania                   1.0   60831.0 NaN   60831.0   60831.0
Rhode Island                   1.0   41623.0 NaN   41623.0   41623.0
South Carolina                 1.0    9921.0 NaN    9921.0    9921.0
South Dakota                   1.0    7954.0 NaN    7954.0    7954.0
Tennessee                      1.0   40445.0 NaN   40445.0   40445.0
Texas                          1.0  479959.0 NaN  479959.0  479959.0
U.S. Marshalls                 0.0       NaN NaN       NaN       NaN
Utah                           1.0   27053.0 NaN   27053.0   27053.0
Vermont                        1.0   19838.0 NaN   19838.0   19838.0
Virginia                       1.0   99317.0 NaN   99317.0   99317.0
Washington                     1.0   11022.0 NaN   11022.0   11022.0
West Virginia                  1.0   10778.0 NaN   10778.0   10778.0
Wisconsin                      1.0   97445.0 NaN   97445.0   97445.0
Wyoming                        1.0   28376.0 NaN   28376.0   28376.0

                                                    total_inmate_cases  \
                            50%       75%       max              count
system
Alabama                 15505.0   15505.0   15505.0                1.0
Alaska                  27756.0   27756.0   27756.0                1.0
Arizona                 43652.0   43652.0   43652.0                1.0
Arkansas                    0.0       0.0       0.0                1.0
California             121207.0  121207.0  121207.0                1.0
Colorado               193165.0  193165.0  193165.0                1.0
Connecticut             73559.0   73559.0   73559.0                1.0
County jails           460887.0  460887.0  460887.0                1.0
Delaware                12665.0   12665.0   12665.0                1.0
Federal Prisons        119449.0  119449.0  119449.0                1.0
Florida                 87677.0   87677.0   87677.0                1.0
Georgia                 11947.0   11947.0   11947.0                1.0
Hawaii                   7791.0    7791.0    7791.0                1.0
ICE detention centers  101214.0  101214.0  101214.0                1.0
Idaho                   29168.0   29168.0   29168.0                1.0
Illinois               477218.0  477218.0  477218.0                1.0
Indiana                 20228.0   20228.0   20228.0                1.0
Iowa                    44262.0   44262.0   44262.0                1.0
Kansas                  43391.0   43391.0   43391.0                1.0
Kentucky                26433.0   26433.0   26433.0                1.0
Louisiana               14745.0   14745.0   14745.0                1.0
Maine                    8246.0    8246.0    8246.0                1.0
Maryland                65158.0   65158.0   65158.0                1.0
Massachusetts           29016.0   29016.0   29016.0                1.0
Michigan               673822.0  673822.0  673822.0                1.0
Minnesota              105390.0  105390.0  105390.0                1.0
Mississippi              3433.0    3433.0    3433.0                1.0
Missouri                92520.0   92520.0   92520.0                1.0
Montana                     0.0       0.0       0.0                1.0
Nebraska                 6776.0    6776.0    6776.0                1.0
Nevada                  12368.0   12368.0   12368.0                1.0
New Hampshire            1583.0    1583.0    1583.0                1.0
New Jersey             251841.0  251841.0  251841.0                1.0
New Mexico              44368.0   44368.0   44368.0                1.0
New York                73607.0   73607.0   73607.0                1.0
North Carolina         124617.0  124617.0  124617.0                1.0
North Dakota            32531.0   32531.0   32531.0                1.0
Ohio                    56275.0   56275.0   56275.0                1.0
Oklahoma                30802.0   30802.0   30802.0                1.0
Oregon                  24852.0   24852.0   24852.0                1.0
Pennsylvania            60831.0   60831.0   60831.0                1.0
Rhode Island            41623.0   41623.0   41623.0                1.0
South Carolina           9921.0    9921.0    9921.0                1.0
South Dakota             7954.0    7954.0    7954.0                1.0
Tennessee               40445.0   40445.0   40445.0                1.0
Texas                  479959.0  479959.0  479959.0                1.0
U.S. Marshalls              NaN       NaN       NaN                1.0
Utah                    27053.0   27053.0   27053.0                1.0
Vermont                 19838.0   19838.0   19838.0                1.0
Virginia                99317.0   99317.0   99317.0                1.0
Washington              11022.0   11022.0   11022.0                1.0
West Virginia           10778.0   10778.0   10778.0                1.0
Wisconsin               97445.0   97445.0   97445.0                1.0
Wyoming                 28376.0   28376.0   28376.0                1.0

                                 ... total_officer_cases           \
                           mean  ...                 75%      max
system                           ...
Alabama                  1601.0  ...              1019.0   1019.0
Alaska                   2428.0  ...                85.0     85.0
Arizona                 12229.0  ...              2739.0   2739.0
Arkansas                11378.0  ...               424.0    424.0
California              49511.0  ...             16090.0  16090.0
Colorado                 9389.0  ...              1834.0   1834.0
Connecticut              4655.0  ...              1571.0   1571.0
County jails           108082.0  ...             33421.0  33421.0
Delaware                 2020.0  ...               514.0    514.0
Federal Prisons         53996.0  ...              6746.0   6746.0
Florida                 18491.0  ...              6097.0   6097.0
Georgia                  3717.0  ...              1698.0   1698.0
Hawaii                   1432.0  ...                99.0     99.0
ICE detention centers   10845.0  ...                53.0     53.0
Idaho                    4115.0  ...               387.0    387.0
Illinois                10894.0  ...              4383.0   4383.0
Indiana                  3563.0  ...              1571.0   1571.0
Iowa                     4935.0  ...               806.0    806.0
Kansas                   6202.0  ...              1280.0   1280.0
Kentucky                 7898.0  ...              1084.0   1084.0
Louisiana                3195.0  ...               925.0    925.0
Maine                     169.0  ...                45.0     45.0
Maryland                 4083.0  ...              2168.0   2168.0
Massachusetts            3018.0  ...               629.0    629.0
Michigan                26243.0  ...              3763.0   3763.0
Minnesota                4042.0  ...               967.0    967.0
Mississippi              1470.0  ...               220.0    220.0
Missouri                 5705.0  ...              2709.0   2709.0
Montana                  1148.0  ...               279.0    279.0
Nebraska                  982.0  ...               511.0    511.0
Nevada                   4714.0  ...              1018.0   1018.0
New Hampshire             453.0  ...               155.0    155.0
New Jersey               4684.0  ...              2121.0   2121.0
New Mexico               3124.0  ...               895.0    895.0
New York                 6334.0  ...              4976.0   4976.0
North Carolina          10066.0  ...              2186.0   2186.0
North Dakota              639.0  ...               296.0    296.0
Ohio                     8679.0  ...              4783.0   4783.0
Oklahoma                 7392.0  ...              1043.0   1043.0
Oregon                   3617.0  ...               857.0    857.0
Pennsylvania            10191.0  ...              4090.0   4090.0
Rhode Island             1194.0  ...               322.0    322.0
South Carolina           3254.0  ...               953.0    953.0
South Dakota             2355.0  ...               190.0    190.0
Tennessee                6637.0  ...              1182.0   1182.0
Texas                   34735.0  ...             11895.0  11895.0
U.S. Marshalls          12290.0  ...                 NaN      NaN
Utah                     3443.0  ...               399.0    399.0
Vermont                   456.0  ...                89.0     89.0
Virginia                 9056.0  ...              2466.0   2466.0
Washington               6190.0  ...              1026.0   1026.0
West Virginia            1576.0  ...               578.0    578.0
Wisconsin               10939.0  ...              2129.0   2129.0
Wyoming                   879.0  ...               296.0    296.0

                      total_officer_deaths                                    \
                                     count  mean std   min   25%   50%   75%
system
Alabama                                1.0   3.0 NaN   3.0   3.0   3.0   3.0
Alaska                                 1.0   0.0 NaN   0.0   0.0   0.0   0.0
Arizona                                1.0   0.0 NaN   0.0   0.0   0.0   0.0
Arkansas                               1.0   5.0 NaN   5.0   5.0   5.0   5.0
California                             1.0  26.0 NaN  26.0  26.0  26.0  26.0
Colorado                               1.0   0.0 NaN   0.0   0.0   0.0   0.0
Connecticut                            1.0   0.0 NaN   0.0   0.0   0.0   0.0
County jails                           1.0  82.0 NaN  82.0  82.0  82.0  82.0
Delaware                               1.0   1.0 NaN   1.0   1.0   1.0   1.0
Federal Prisons                        1.0   4.0 NaN   4.0   4.0   4.0   4.0
Florida                                1.0   7.0 NaN   7.0   7.0   7.0   7.0
Georgia                                1.0   4.0 NaN   4.0   4.0   4.0   4.0
Hawaii                                 1.0   0.0 NaN   0.0   0.0   0.0   0.0
ICE detention centers                  1.0   0.0 NaN   0.0   0.0   0.0   0.0
Idaho                                  1.0   0.0 NaN   0.0   0.0   0.0   0.0
Illinois                               1.0   0.0 NaN   0.0   0.0   0.0   0.0
Indiana                                1.0   4.0 NaN   4.0   4.0   4.0   4.0
Iowa                                   1.0   2.0 NaN   2.0   2.0   2.0   2.0
Kansas                                 1.0   6.0 NaN   6.0   6.0   6.0   6.0
Kentucky                               1.0   5.0 NaN   5.0   5.0   5.0   5.0
Louisiana                              1.0   6.0 NaN   6.0   6.0   6.0   6.0
Maine                                  1.0   0.0 NaN   0.0   0.0   0.0   0.0
Maryland                               1.0   3.0 NaN   3.0   3.0   3.0   3.0
Massachusetts                          1.0   0.0 NaN   0.0   0.0   0.0   0.0
Michigan                               1.0   3.0 NaN   3.0   3.0   3.0   3.0
Minnesota                              1.0   0.0 NaN   0.0   0.0   0.0   0.0
Mississippi                            1.0   0.0 NaN   0.0   0.0   0.0   0.0
Missouri                               1.0   6.0 NaN   6.0   6.0   6.0   6.0
Montana                                1.0   0.0 NaN   0.0   0.0   0.0   0.0
Nebraska                               1.0   0.0 NaN   0.0   0.0   0.0   0.0
Nevada                                 1.0   3.0 NaN   3.0   3.0   3.0   3.0
New Hampshire                          1.0   0.0 NaN   0.0   0.0   0.0   0.0
New Jersey                             1.0   3.0 NaN   3.0   3.0   3.0   3.0
New Mexico                             1.0   1.0 NaN   1.0   1.0   1.0   1.0
New York                               1.0   8.0 NaN   8.0   8.0   8.0   8.0
North Carolina                         1.0   1.0 NaN   1.0   1.0   1.0   1.0
North Dakota                           1.0   1.0 NaN   1.0   1.0   1.0   1.0
Ohio                                   1.0  11.0 NaN  11.0  11.0  11.0  11.0
Oklahoma                               1.0   2.0 NaN   2.0   2.0   2.0   2.0
Oregon                                 1.0   0.0 NaN   0.0   0.0   0.0   0.0
Pennsylvania                           1.0   5.0 NaN   5.0   5.0   5.0   5.0
Rhode Island                           1.0   1.0 NaN   1.0   1.0   1.0   1.0
South Carolina                         1.0   2.0 NaN   2.0   2.0   2.0   2.0
South Dakota                           1.0   0.0 NaN   0.0   0.0   0.0   0.0
Tennessee                              1.0   2.0 NaN   2.0   2.0   2.0   2.0
Texas                                  1.0  44.0 NaN  44.0  44.0  44.0  44.0
U.S. Marshalls                         0.0   NaN NaN   NaN   NaN   NaN   NaN
Utah                                   1.0   0.0 NaN   0.0   0.0   0.0   0.0
Vermont                                1.0   0.0 NaN   0.0   0.0   0.0   0.0
Virginia                               1.0   5.0 NaN   5.0   5.0   5.0   5.0
Washington                             1.0   2.0 NaN   2.0   2.0   2.0   2.0
West Virginia                          1.0   2.0 NaN   2.0   2.0   2.0   2.0
Wisconsin                              1.0   0.0 NaN   0.0   0.0   0.0   0.0
Wyoming                                1.0   0.0 NaN   0.0   0.0   0.0   0.0


                        max
system
Alabama                 3.0
Alaska                  0.0
Arizona                 0.0
Arkansas                5.0
California             26.0
Colorado                0.0
Connecticut             0.0
County jails           82.0
Delaware                1.0
Federal Prisons         4.0
Florida                 7.0
Georgia                 4.0
Hawaii                  0.0
ICE detention centers   0.0
Idaho                   0.0
Illinois                0.0
Indiana                 4.0
Iowa                    2.0
Kansas                  6.0
Kentucky                5.0
Louisiana               6.0
Maine                   0.0
Maryland                3.0
Massachusetts           0.0
Michigan                3.0
Minnesota               0.0
Mississippi             0.0
Missouri                6.0
Montana                 0.0
Nebraska                0.0
Nevada                  3.0
New Hampshire           0.0
New Jersey              3.0
New Mexico              1.0
New York                8.0
North Carolina          1.0
North Dakota            1.0
Ohio                   11.0
Oklahoma                2.0
Oregon                  0.0
Pennsylvania            5.0
Rhode Island            1.0
South Carolina          2.0
South Dakota            0.0
Tennessee               2.0
Texas                  44.0
U.S. Marshalls          NaN
Utah                    0.0
Vermont                 0.0
Virginia                5.0
Washington              2.0
West Virginia           2.0
Wisconsin               0.0
Wyoming                 0.0

[54 rows x 56 columns]

In [33]:
data_dt = pd.read_excel("./datasets/CPP_long_6-21-21.xlsx")

In [34]:
data_dt.head()

,scrapedate,lastupdated,stateagency,facility,fac_inc_positive,fac_inc_activeasymptomatic,sum_inc_tested,fac_inc_activesymptomatic,sum_inc_hospitalized,sum_inc_recovered,...,bjs_fac_security,bjs_fac_leave,bjs_fac_operator,bjs_fac_malepop,bjs_fac_femalepop,bjs_fac_linked,bjs_fac_linktxt,bjs_fac_changeuse,bjs_fac_changeclose,oldnew
0,2020-05-22,NR,CT,Bridgeport CC,66.0,NR,NR,NR,NR,NR,...,Maximum/close/high,None,State authority,865.0,NR,No,NR,No,No,old
1,2020-05-22,NaN,CT,Brooklyn CI,19.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,old
2,2020-05-22,NaN,CT,Carl Robinson CI,75.0,NaN,NaN,NaN,NaN,NaN,...,Medium,None,State authority,1459.0,NaN,No,NaN,No,No,old
3,2020-05-22,NaN,CT,Cheshire CI,18.0,NaN,NaN,NaN,NaN,NaN,...,Maximum/close/high,None,State authority,1471.0,NaN,No,NaN,No,No,old
4,2020-05-22,NaN,CT,Corrigan-Radgowski,110.0,NaN,NaN,NaN,NaN,NaN,...,Maximum/close/high,None,State authority,1556.0,NaN,No,NaN,No,No,old